// The offline service worker (docs/sw.js, generated by build.js) — previously untested (full review §8).
// Runs the real built file in a vm with a fake cache store, fetch and timers.
const test=require('node:test'),assert=require('node:assert');
const vm=require('vm'),fs=require('fs'),path=require('path');
const VERSION=require('../package.json').version,V='ironlog-'+VERSION;
const SW=fs.readFileSync(path.join(__dirname,'..','docs','sw.js'),'utf8');
const PAGE='https://me.github.io/ironlog/';

function loadSW(fetchImpl){
  const listeners={},store={};let timers=[];
  const keyOf=r=>typeof r==='string'?r:r.url;
  const caches={
    open:async n=>{store[n]=store[n]||new Map();return {addAll:async reqs=>{reqs.forEach(r=>store[n].set(keyOf(r),{ok:true,body:'asset'}));},put:async(req,res)=>{store[n].set(keyOf(req),res);}};},
    match:async req=>{const k=keyOf(req);for(const n of Object.keys(store))if(store[n].has(k))return store[n].get(k);return undefined;},
    keys:async()=>Object.keys(store),delete:async n=>{delete store[n];return true;}
  };
  const ctx={self:{addEventListener:(t,f)=>{listeners[t]=f;},skipWaiting:()=>{},clients:{claim:()=>{}}},caches,fetch:fetchImpl,URL,
    location:{origin:'https://me.github.io'},Request:function(u,o){this.url=u;this.opts=o;},Response:{error:()=>({error:true})},
    setTimeout:f=>{timers.push(f);return timers.length;},clearTimeout:id=>{timers[id-1]=null;},Promise,console};
  vm.createContext(ctx);vm.runInContext(SW,ctx);
  return {listeners,store,fireTimers:()=>{const t=timers;timers=[];t.forEach(f=>f&&f());}};
}
function navigate(sw){let resp;const waits=[];
  sw.listeners.fetch({request:{url:PAGE,mode:'navigate',method:'GET',destination:'document'},respondWith:p=>{resp=p;},waitUntil:p=>waits.push(p)});
  return {resp,waits};}
const seedCache=sw=>{sw.store[V]=new Map([[PAGE,{ok:true,body:'saved copy'}]]);};

test('gym "lie-fi": a network that hangs falls back to the saved copy after the timeout',async()=>{
  const sw=loadSW(()=>new Promise(()=>{}));   // never resolves, never fails
  seedCache(sw);
  const {resp}=navigate(sw);
  sw.fireTimers();   // the 3 s timeout
  const r=await resp;
  assert.equal(r.body,'saved copy','served the saved copy instead of a blank screen');
});
test('online: the fresh page is served and the saved copy is refreshed',async()=>{
  const fresh={ok:true,body:'new deploy',clone(){return this;}};
  const sw=loadSW(async()=>fresh);seedCache(sw);
  const {resp,waits}=navigate(sw);
  assert.equal((await resp).body,'new deploy');
  await Promise.all(waits);
  assert.equal(sw.store[V].get(PAGE).body,'new deploy','cache updated for next time');
});
test('a server error mid-deploy shows the saved copy, not the error page, and is never cached',async()=>{
  const sw=loadSW(async()=>({ok:false,status:503,body:'error page',clone(){return this;}}));seedCache(sw);
  const {resp,waits}=navigate(sw);
  assert.equal((await resp).body,'saved copy');
  await Promise.all(waits);
  assert.equal(sw.store[V].get(PAGE).body,'saved copy','the 503 did not overwrite the good copy');
});
test('fully offline still works; first visit with no network fails cleanly',async()=>{
  const sw=loadSW(()=>Promise.reject(new Error('offline')));seedCache(sw);
  assert.equal((await navigate(sw).resp).body,'saved copy');
  const empty=loadSW(()=>Promise.reject(new Error('offline')));
  assert.equal((await navigate(empty).resp).error,true,'no saved copy + no network = a clean network error');
});
test('activate deletes only Ironlog’s OLD caches — never another project’s on the shared github.io origin',async()=>{
  const sw=loadSW(async()=>({ok:true}));
  sw.store['ironlog-0.0.1']=new Map();sw.store['someone-elses-app-v2']=new Map();sw.store[V]=new Map();
  const waits=[];sw.listeners.activate({waitUntil:p=>waits.push(p)});await Promise.all(waits);
  assert.ok(!sw.store['ironlog-0.0.1'],'old Ironlog cache removed');
  assert.ok(sw.store['someone-elses-app-v2'],'another project’s cache untouched');
  assert.ok(sw.store[V],'current cache kept');
});
